# Generated by Django 3.2.8 on 2021-10-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_catalog_app', '0002_auto_20211025_1301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
    ]
