# Generated by Django 3.2.8 on 2021-10-26 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dastugo_catalog_app', '0004_auto_20211026_1008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
